version: '3'
services:
  web:
    image: docker-node-express-mongoapp
    build: ./
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
